name: Trigger auto deployment for aca-hello-world-main

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-hello-world-main-AutoDeployTrigger-856142a7-a605-4492-9937-cf6eba443a82.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACAHELLOWORLDMAIN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAHELLOWORLDMAIN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAHELLOWORLDMAIN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: amarregistry1.azurecr.io
          registryUsername: ${{ secrets.ACAHELLOWORLDMAIN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAHELLOWORLDMAIN_REGISTRY_PASSWORD }}
          containerAppName: aca-hello-world-main
          resourceGroup: amar-con-env1
          imageToBuild: amarregistry1.azurecr.io/aca-hello-world-main:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


