name: Trigger auto deployment for amarcon

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/amarcon-AutoDeployTrigger-804af6f3-9b77-4e8b-b23a-63b00d9198d6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AMARCON_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AMARCON_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AMARCON_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: amarregistry1.azurecr.io
          registryUsername: ${{ secrets.AMARCON_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AMARCON_REGISTRY_PASSWORD }}
          containerAppName: amarcon
          resourceGroup: amartest1
          imageToBuild: amarregistry1.azurecr.io/amarcon:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


